export const environment = {
  production: false,
  API_TOKEN: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4ZDY5YWEwNmU1OGRmY2VhODgyMjYzODAzMjQyMjM5MyIsInN1YiI6IjY0Zjc3OTFhZmZjOWRlMDEzOGVhMjYzMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.bwszqgq1_2H8CdUTB26vLVqFIFkIXzBq_2wMYocMYvY',
};
